name: Deploy to Production

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때마다 워크플로우 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build project
        env:
          VITE_NAVER: ${{ secrets.VUE_APP_NAVER_CLIENT_ID }}
        run: npm run build
